version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_web
    ports:
      - "8004:8000"
    command: ./start.sh
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery:
    build: .
    container_name: fastapi_celery
    command: celery -A src.celery_scheduler.celery worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery-beat:
    build: .
    container_name: fastapi_celery_beat
    command: celery -A src.celery_scheduler.celery beat --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: fastapi_redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: fastapi_mailhog
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP

  db:
    image: postgres:17
    container_name: fastapi_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
