
services:

  web:
    build: .
    ports:
      - 8004:8000
    command: ./start.sh
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A src.celery_scheduler.celery worker --loglevel=info
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A src.celery_scheduler.celery beat --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
