"""Create regions and movie_regions tables

Revision ID: e1e09a8a9165
Revises: 943496329c3b
Create Date: 2025-10-03 12:02:25.451638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e09a8a9165'
down_revision: Union[str, Sequence[str], None] = '943496329c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('movie_regions',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'region_id')
    )
    op.execute("""
        INSERT INTO regions (code, name) VALUES
        ('US', 'United States'),
        ('UA', 'Ukraine'),
        ('EU', 'Europe'),
        ('JP', 'Japan'),
        ('IN', 'India'),
        ('CA', 'Canada'),
        ('BR', 'Brazil'),
        ('AU', 'Australia'),
        ('FR', 'France'),
        ('DE', 'Germany')
        ON CONFLICT (code) DO NOTHING;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
